---

## RHEL7x tasks to print out statements for tasks

- name: Debug listing of important variables
  debug: 
    msg: "RHEL7x Tasks START - Customer: {{default_customer_abbrev}} OS Version: {{default_os_ver}}"

- name: Debug listing of important variables part 2
  debug: 
    msg: "RHEL7x Tasks END - BODS Ver: {{default_bods_ver}} OS Version: {{default_os_ver}}"


...
